version: 0.0
os: linux
files:
    - source: ./
      destination: /home/ubuntu/startlens/startlens_django/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root