version: 0.0
os: linux
files:
    - source: ./
      destination: /home/ubuntu/startlens/startlens_django/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/exec_collectstatic
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/restart_gunicorn
      timeout: 300
      runas: ubuntu