version: 0.0
os: linux
files:
    - source: ./
      destination: /home/ubuntu/startlens/startlens_django/
hooks:
  ApplicationStop:
    - location: scripts/delete_redundant.sh
      timeout: 300
      runas: root
  BreforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/exec_collectstatic.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_gunicorn.sh
      timeout: 300
      runas: root