# Generated by Django 2.2.13 on 2020-07-29 07:57

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(default=analysis.models.set_default_thumbnail_path, upload_to=analysis.models.get_thumbnail_path, verbose_name='サムネイル画像'),
        ),
        migrations.AlterField(
            model_name='userlang',
            name='language',
            field=models.CharField(choices=[('NA', ''), ('en', '英語'), ('zh', '中国語'), ('ko', '韓国語')], default='NA', max_length=5, verbose_name='言語'),
        ),
    ]
